TT:
  fill-color: '#cc7a16'
  legend: 't#bar{t}'
  order: 1
  type: mc
  group: TT
  files:
    - TTTo2L2Nu.root
    - TTToHadronic.root
    - TTToSemiLeptonic.root
DY:
  fill-color: '#1a83a1'
  legend: Drell-Yan 
  order: 3
  type: mc
  files:
    - cat: [".*SL.*"]
      files:
        - DYJetsToLL_M-10to50.root
        - DYJetsToLL_M-50.root
        - DYToLL_0J.root
        - DYToLL_1J.root
        - DYToLL_2J.root
    - cat: [".*DL.*"]
      files:
        - DoubleEGamma_2016B0DYEstimation.root
        - DoubleEGamma_2016B1DYEstimation.root
        - DoubleEGamma_2016CDYEstimation.root
        - DoubleEGamma_2016DDYEstimation.root
        - DoubleEGamma_2016EDYEstimation.root
        - DoubleEGamma_2016FDYEstimation.root
        - DoubleEGamma_2016GDYEstimation.root
        - DoubleEGamma_2016H0DYEstimation.root
        - DoubleEGamma_2016H1DYEstimation.root
        - DoubleMuon_2016B0DYEstimation.root
        - DoubleMuon_2016B1DYEstimation.root
        - DoubleMuon_2016CDYEstimation.root
        - DoubleMuon_2016DDYEstimation.root
        - DoubleMuon_2016EDYEstimation.root
        - DoubleMuon_2016FDYEstimation.root
        - DoubleMuon_2016GDYEstimation.root
        - DoubleMuon_2016H0DYEstimation.root
        - DoubleMuon_2016H1DYEstimation.root
        - GluGluHToBBDYEstimation.root
        - GluGluHToGGDYEstimation.root
        - GluGluHToMuMuDYEstimation.root
        - GluGluHToTauTauDYEstimation.root
        - GluGluHToWWTo2L2NuDYEstimation.root
        - GluGluHToWWToLNuQQDYEstimation.root
        - GluGluHToZZTo4LDYEstimation.root
        - HZJ_HToWWDYEstimation.root
        - MuonEG_2016B0DYEstimation.root
        - MuonEG_2016B1DYEstimation.root
        - MuonEG_2016CDYEstimation.root
        - MuonEG_2016DDYEstimation.root
        - MuonEG_2016EDYEstimation.root
        - MuonEG_2016FDYEstimation.root
        - MuonEG_2016GDYEstimation.root
        - MuonEG_2016H0DYEstimation.root
        - MuonEG_2016H1DYEstimation.root
        - SingleElectron_2016B0DYEstimation.root
        - SingleElectron_2016B1DYEstimation.root
        - SingleElectron_2016CDYEstimation.root
        - SingleElectron_2016DDYEstimation.root
        - SingleElectron_2016EDYEstimation.root
        - SingleElectron_2016FDYEstimation.root
        - SingleElectron_2016GDYEstimation.root
        - SingleElectron_2016H0DYEstimation.root
        - SingleElectron_2016H1DYEstimation.root
        - SingleMuon_2016B0DYEstimation.root
        - SingleMuon_2016B1DYEstimation.root
        - SingleMuon_2016CDYEstimation.root
        - SingleMuon_2016DDYEstimation.root
        - SingleMuon_2016EDYEstimation.root
        - SingleMuon_2016FDYEstimation.root
        - SingleMuon_2016GDYEstimation.root
        - SingleMuon_2016H0DYEstimation.root
        - SingleMuon_2016H1DYEstimation.root
        - ST_schannel_4fDYEstimation.root
        - ST_tchannel_antitop_4fDYEstimation.root
        - ST_tchannel_top_4fDYEstimation.root
        - ST_tW_antitop_5fDYEstimation.root
        - ST_tWll_5fDYEstimation.root
        - ST_tW_top_5fDYEstimation.root
        - TGJetsDYEstimation.root
        - THQDYEstimation.root
        - THWDYEstimation.root
        - TTGJetsDYEstimation.root
        - ttHJetTobbDYEstimation.root
        - ttHJetToNonbbDYEstimation.root
        - TTTo2L2NuDYEstimation.root
        - TTToHadronicDYEstimation.root
        - TTToSemiLeptonicDYEstimation.root
        - TTTTDYEstimation.root
        - TTWHDYEstimation.root
        - TTWJetsToLNuDYEstimation.root
        - TTWJetsToQQDYEstimation.root
        - TTWWDYEstimation.root
        - TTZHDYEstimation.root
        - TTZToLL_M-1to10DYEstimation.root
        - TTZToLLNuNu_M-10DYEstimation.root
        - TTZToQQDYEstimation.root
        - tZq_llDYEstimation.root
        - VBFHToBBDYEstimation.root
        - VBFHToGGDYEstimation.root
        - VBFHToMuMuDYEstimation.root
        - VBFHToTauTauDYEstimation.root
        - VBFHToWWTo2L2NuDYEstimation.root
        - VBFHToWWToLNuQQDYEstimation.root
        - VBFHToZZTo4LDYEstimation.root
        - VHToNonbbDYEstimation.root
        - W1JetsToLNuDYEstimation.root
        - W2JetsToLNuDYEstimation.root
        - W3JetsToLNuDYEstimation.root
        - W4JetsToLNuDYEstimation.root
        - WGToLNuGDYEstimation.root
        - WJetsToLNuDYEstimation.root
        - WJetsToLNu_HT-100To200DYEstimation.root
        - WJetsToLNu_HT-1200To2500DYEstimation.root
        - WJetsToLNu_HT-200To400DYEstimation.root
        - WJetsToLNu_HT-2500ToInfDYEstimation.root
        - WJetsToLNu_HT-400To600DYEstimation.root
        - WJetsToLNu_HT-600To800DYEstimation.root
        - WJetsToLNu_HT-70To100DYEstimation.root
        - WJetsToLNu_HT-800To1200DYEstimation.root
        - WminusH_HToBB_WToLNuDYEstimation.root
        - WplusH_HToBB_WToLNuDYEstimation.root
        - WpWpJJDYEstimation.root
        - WWTo2L2Nu_DoubleScatteringDYEstimation.root
        - WWTo2L2NuDYEstimation.root
        - WWToLNuQQDYEstimation.root
        - WWWDYEstimation.root
        - WWZDYEstimation.root
        - WZGDYEstimation.root
        - WZTo2L2QDYEstimation.root
        - WZTo3LNuDYEstimation.root
        - WZZDYEstimation.root
        - ZGTo2LGDYEstimation.root
        - ZH_HToBB_ZToLLDYEstimation.root
        - ZHToTauTauDYEstimation.root
        - ZZTo2L2QDYEstimation.root
        - ZZTo4LDYEstimation.root
        - ZZZDYEstimation.root

ST:
  fill-color: '#99053d'
  legend: Single Top
  order: 2
  type: mc
  group: ST
  files:
    - ST_schannel_4f.root
    - ST_tchannel_antitop_4f.root
    - ST_tchannel_top_4f.root
    - ST_tW_antitop_5f.root
    - ST_tWll_5f.root
    - ST_tW_top_5f.root
WJets:
  fill-color: '#d95564'
  legend: W+jets
  order: 4
  type: mc
  group: WJets
  files:
    - WJetsToLNu_HT-100To200.root
    - WJetsToLNu_HT-1200To2500.root
    - WJetsToLNu_HT-200To400.root
    - WJetsToLNu_HT-2500ToInf.root
    - WJetsToLNu_HT-400To600.root
    - WJetsToLNu_HT-600To800.root
    - WJetsToLNu_HT-70To100.root
    - WJetsToLNu_HT-800To1200.root
    - WJetsToLNu.root
    - W1JetsToLNu.root
    - W2JetsToLNu.root
    - W3JetsToLNu.root
    - W4JetsToLNu.root
VV:  
  fill-color: '#ccbf45'
  legend: VV(V)
  group: VVV
  order: 5
  type: mc
  files:
    - WWTo2L2Nu_DoubleScattering.root
    - WWTo2L2Nu.root
    - WWToLNuQQ.root
    - WZG.root
    - WZTo2L2Q.root
    - WZTo3LNu.root
    - ZZTo2L2Q.root
    - ZZTo4L.root
VVV:  
  fill-color: '#ccbf45'
  legend: VV(V)
  group: VVV
  order: 5
  type: mc
  files:
    - WWW.root
    - WWZ.root
    - WZZ.root
    - ZZZ.root
ggH_hbb:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 7
  type: mc
  files:
    - GluGluHToBB.root
ggH_hgg:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 7
  type: mc
  files:
    - GluGluHToGG.root
ggH_hmm:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 7
  type: mc
  files:
    - GluGluHToMuMu.root
ggH_htt:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 7
  type: mc
  files:
    - GluGluHToTauTau.root
ggH_hww:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 7
  type: mc
  files:
    - GluGluHToWWTo2L2Nu.root
    - GluGluHToWWToLNuQQ.root
ggH_hzz:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 7
  type: mc
  files:
    - GluGluHToZZTo4L.root
    - GluGluHToZZTo2L2Q.root
qqH_hbb:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 8
  type: mc
  files:
    - VBFHToBB.root
qqH_hgg:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 8
  type: mc
  files:
    - VBFHToGG.root
qqH_hmm:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 8
  type: mc
  files:
    - VBFHToMuMu.root
qqH_htt:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 8
  type: mc
  files:
    - VBFHToTauTau.root
qqH_hww:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 8
  type: mc
  files:
    - VBFHToWWTo2L2Nu.root
    - VBFHToWWToLNuQQ.root
qqH_hzz:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 8
  type: mc
  files:
    - VBFHToZZTo4L.root
ttH_hbb:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 9
  type: mc
  files:
    - ttHJetTobb.root
ttH_hww:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 9
  type: mc
  files:
    - ttHJetToNonbb.root
WH_hbb:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 10
  type: mc
  files:
    - WminusH_HToBB_WToLNu.root
    - WplusH_HToBB_WToLNu.root
ZH_hbb:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 11
  type: mc
  files:
    - ZH_HToBB_ZToLL.root
ZH_htt:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 11
  type: mc
  files:
    - ZHToTauTau.root
ZH_hww:
  legend: SM H
  fill-color: '#06b894'
  group: SM
  order: 11
  type: mc
  files:
    - HZJ_HToWW.root
tHq_hww:
  fill-color: '#06b894'
  legend: SM H
  group: SM
  order: 7
  type: mc
  files:
    - THQ.root
tHW_hww:
  fill-color: '#06b894'
  legend: SM H
  group: SM
  order: 7
  type: mc
  files:
    - THW.root
VH_hww:
  fill-color: '#06b894'
  legend: SM H
  group: SM
  order: 7
  type: mc
  files:
    - VHToNonbb.root

ttZ:
  fill-color: '#610596'
  legend: ttZ
  order: 12
  type: mc
  group: Rares
  files:
    - TTZH.root
    - TTZToLL_M-1to10.root
    - TTZToLLNuNu_M-10.root
    - TTZToQQ.root

ttW:
  fill-color: '#610596'
  legend: ttW
  order: 12
  type: mc
  group: Rares
  files:
    - TTWH.root
    - TTWJetsToLNu.root
    - TTWJetsToQQ.root
    - TTWW.root

Other_bbWW:
  fill-color: '#610596'
  legend: Rares 
  order: 12
  type: mc
  group: Rares
  files:
    - TTGJets.root
    - TGJets.root
    - TTTT.root
    - WGToLNuG.root
    - ZGTo2LG.root
    - WpWpJJ.root
    - tZq_ll.root
