Fakes: 
  fill-color: '#6e3303'
  legend: Fakes
  order: 13
  type: mc
  group: Fakes
  files:
    - DoubleEGamma_2016B0FakeExtrapolation.root
    - DoubleEGamma_2016B1FakeExtrapolation.root
    - DoubleEGamma_2016CFakeExtrapolation.root
    - DoubleEGamma_2016DFakeExtrapolation.root
    - DoubleEGamma_2016EFakeExtrapolation.root
    - DoubleEGamma_2016FFakeExtrapolation.root
    - DoubleEGamma_2016GFakeExtrapolation.root
    - DoubleEGamma_2016H0FakeExtrapolation.root
    - DoubleEGamma_2016H1FakeExtrapolation.root
    - DoubleMuon_2016B0FakeExtrapolation.root
    - DoubleMuon_2016B1FakeExtrapolation.root
    - DoubleMuon_2016CFakeExtrapolation.root
    - DoubleMuon_2016DFakeExtrapolation.root
    - DoubleMuon_2016EFakeExtrapolation.root
    - DoubleMuon_2016FFakeExtrapolation.root
    - DoubleMuon_2016GFakeExtrapolation.root
    - DoubleMuon_2016H0FakeExtrapolation.root
    - DoubleMuon_2016H1FakeExtrapolation.root
    - DYJetsToLL_M-10to50FakeExtrapolation.root
    - DYJetsToLL_M-50FakeExtrapolation.root
    - DYToLL_0JFakeExtrapolation.root
    - DYToLL_1JFakeExtrapolation.root
    - DYToLL_2JFakeExtrapolation.root
    - GluGluHToBBFakeExtrapolation.root
    - GluGluHToGGFakeExtrapolation.root
    - GluGluHToMuMuFakeExtrapolation.root
    - GluGluHToTauTauFakeExtrapolation.root
    - GluGluHToWWTo2L2NuFakeExtrapolation.root
    - GluGluHToWWToLNuQQFakeExtrapolation.root
    - GluGluHToZZTo4LFakeExtrapolation.root
    - HZJ_HToWWFakeExtrapolation.root
    - MuonEG_2016B0FakeExtrapolation.root
    - MuonEG_2016B1FakeExtrapolation.root
    - MuonEG_2016CFakeExtrapolation.root
    - MuonEG_2016DFakeExtrapolation.root
    - MuonEG_2016EFakeExtrapolation.root
    - MuonEG_2016FFakeExtrapolation.root
    - MuonEG_2016GFakeExtrapolation.root
    - MuonEG_2016H0FakeExtrapolation.root
    - MuonEG_2016H1FakeExtrapolation.root
    - SingleElectron_2016B0FakeExtrapolation.root
    - SingleElectron_2016B1FakeExtrapolation.root
    - SingleElectron_2016CFakeExtrapolation.root
    - SingleElectron_2016DFakeExtrapolation.root
    - SingleElectron_2016EFakeExtrapolation.root
    - SingleElectron_2016FFakeExtrapolation.root
    - SingleElectron_2016GFakeExtrapolation.root
    - SingleElectron_2016H0FakeExtrapolation.root
    - SingleElectron_2016H1FakeExtrapolation.root
    - SingleMuon_2016B0FakeExtrapolation.root
    - SingleMuon_2016B1FakeExtrapolation.root
    - SingleMuon_2016CFakeExtrapolation.root
    - SingleMuon_2016DFakeExtrapolation.root
    - SingleMuon_2016EFakeExtrapolation.root
    - SingleMuon_2016FFakeExtrapolation.root
    - SingleMuon_2016GFakeExtrapolation.root
    - SingleMuon_2016H0FakeExtrapolation.root
    - SingleMuon_2016H1FakeExtrapolation.root
    - ST_schannel_4fFakeExtrapolation.root
    - ST_tchannel_antitop_4fFakeExtrapolation.root
    - ST_tchannel_top_4fFakeExtrapolation.root
    - ST_tW_antitop_5fFakeExtrapolation.root
    - ST_tWll_5fFakeExtrapolation.root
    - ST_tW_top_5fFakeExtrapolation.root
    - TGJetsFakeExtrapolation.root
    - THQFakeExtrapolation.root
    - THWFakeExtrapolation.root
    - TTGJetsFakeExtrapolation.root
    - ttHJetTobbFakeExtrapolation.root
    - ttHJetToNonbbFakeExtrapolation.root
    - TTTo2L2NuFakeExtrapolation.root
    - TTToHadronicFakeExtrapolation.root
    - TTToSemiLeptonicFakeExtrapolation.root
    - TTTTFakeExtrapolation.root
    - TTWHFakeExtrapolation.root
    - TTWJetsToLNuFakeExtrapolation.root
    - TTWJetsToQQFakeExtrapolation.root
    - TTWWFakeExtrapolation.root
    - TTZHFakeExtrapolation.root
    - TTZToLL_M-1to10FakeExtrapolation.root
    - TTZToLLNuNu_M-10FakeExtrapolation.root
    - TTZToQQFakeExtrapolation.root
    - tZq_llFakeExtrapolation.root
    - VBFHToBBFakeExtrapolation.root
    - VBFHToGGFakeExtrapolation.root
    - VBFHToMuMuFakeExtrapolation.root
    - VBFHToTauTauFakeExtrapolation.root
    - VBFHToWWTo2L2NuFakeExtrapolation.root
    - VBFHToWWToLNuQQFakeExtrapolation.root
    - VBFHToZZTo4LFakeExtrapolation.root
    - VHToNonbbFakeExtrapolation.root
    - W1JetsToLNuFakeExtrapolation.root
    - W2JetsToLNuFakeExtrapolation.root
    - W3JetsToLNuFakeExtrapolation.root
    - W4JetsToLNuFakeExtrapolation.root
    - WGToLNuGFakeExtrapolation.root
    - WJetsToLNuFakeExtrapolation.root
    - WJetsToLNu_HT-100To200FakeExtrapolation.root
    - WJetsToLNu_HT-1200To2500FakeExtrapolation.root
    - WJetsToLNu_HT-200To400FakeExtrapolation.root
    - WJetsToLNu_HT-2500ToInfFakeExtrapolation.root
    - WJetsToLNu_HT-400To600FakeExtrapolation.root
    - WJetsToLNu_HT-600To800FakeExtrapolation.root
    - WJetsToLNu_HT-70To100FakeExtrapolation.root
    - WJetsToLNu_HT-800To1200FakeExtrapolation.root
    - WminusH_HToBB_WToLNuFakeExtrapolation.root
    - WplusH_HToBB_WToLNuFakeExtrapolation.root
    - WpWpJJFakeExtrapolation.root
    - WWTo2L2Nu_DoubleScatteringFakeExtrapolation.root
    - WWTo2L2NuFakeExtrapolation.root
    - WWToLNuQQFakeExtrapolation.root
    - WWWFakeExtrapolation.root
    - WWZFakeExtrapolation.root
    - WZGFakeExtrapolation.root
    - WZTo2L2QFakeExtrapolation.root
    - WZTo3LNuFakeExtrapolation.root
    - WZZFakeExtrapolation.root
    - ZGTo2LGFakeExtrapolation.root
    - ZH_HToBB_ZToLLFakeExtrapolation.root
    - ZHToTauTauFakeExtrapolation.root
    - ZZTo2L2QFakeExtrapolation.root
    - ZZTo4LFakeExtrapolation.root
    - ZZZFakeExtrapolation.root

